# Generated by Django 5.1.1 on 2024-11-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_staticimage_alter_post_image'),
    ]

    operations = [
    ]
